# permissions for end users to edit kbsconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kbsconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: trustee-operator
    app.kubernetes.io/part-of: trustee-operator
    app.kubernetes.io/managed-by: kustomize
  name: kbsconfig-editor-role
rules:
- apiGroups:
  - confidentialcontainers.org
  resources:
  - kbsconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - confidentialcontainers.org
  resources:
  - kbsconfigs/status
  verbs:
  - get
